### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by ghost** [byt3smith/malstrom#6]
Hello, you do not use the most recent ruby version. Do you plan on upgrading Malstrom ?

**Comment by byt3smith** [comment]
@Lodags good question. Currently the Ruby version utilized is `2.1.4`. It is on my short list of things to fix to get up to the latest version though.

**Comment by Lodags** [comment]
Thank you for your answer ! I am currently testing threat intelligence softwares, and it seems that a lot are not up-to-date :'(

**Comment by byt3smith** [comment]
This has been addressed. Malstrom now operates at version `2.4.2`
